const genreList: { [key: string]: string } = {
    "Action": "1",
    "Adventure": "2",
    "Avant Garde": "5",
    "Award Winning": "46",
    "Comedy": "4",
    "Drama": "8",
    "Fantasy": "10",
    "Horror": "14",
    "Mystery": "7",
    "Romance": "22",
    "Sci-Fi": "24",
    "Slice of Life": "36",
    "Sports": "30",
    "Supernatural": "37",
    "Suspense": "41",
    "Combat Sports": "54",
    "Detective": "39",
    "Historical": "13",
    "Isekai": "62",
    "Martial Arts": "17",
    "Mecha": "18",
    "Medical": "67",
    "Military": "38",
    "Music": "19",
    "Parody": "20",
    "Psychological": "40",
    "School": "23",
    "Space": "29",
    "Team Sports": "77",
    "Time Travel": "78",
    "Video Game": "79",
    "Workplace": "48",
    "Josei": "43",
    "Seinen": "42",
    "Shoujo": "25",
    "Shounen": "27",

};
export default genreList;