const genreList: { [key: string]: string } = {
    "Action": "action",
    "Adventure": "adventure",
    "Avant Garde": "avannte-garde",
    "Award Winning": "award winning",
    "Comedy": "comedy",
    "Drama": "drama",
    "Fantasy": "fantasy",
    "Horror": "horror",
    "Mystery": "mystery",
    "Romance": "romance",
    "Sci-Fi": "sci-fi",
    "Slice of Life": "slice of life",
    "Sports": "sports",
    "Supernatural": "supernatural",
    "Suspense": "suspense",
    "Combat Sports": "combat sports",
    "Detective": "detective",
    "Historical": "historical",
    "Isekai": "isekai",
    "Martial Arts": "martial arts",
    "Mecha": "mecha",
    "Medical": "medical",
    "Military": "military",
    "Music": "music",
    "Parody": "parody",
    "Psychological": "psychological",
    "School": "school",
    "Space": "space",
    "Team Sports": "team sports",
    "Time Travel": "time travel",
    "Video Game": "video game",
    "Workplace": "workplace",
    "Josei": "josei",
    "Seinen": "seinen",
    "Shoujo": "shoujo",
    "Shounen": "shounen",

};
export default genreList;